
[env]
platform = https://github.com/CommunityGD32Cores/platform-gd32.git
platform_packages = framework-spl-gd32@git@github.com:morgonxak/framework-spl-gd32.git
monitor_speed = 115200
monitor_echo = yes
upload_protocol = stlink
debug_tool = stlink

[env:gd32l233k_start]
board = gd32l233k_start
framework = spl
build_flags = 
    ; Определение микроконтроллера
    -DGD32L23x    
    ; Специфичные для GD32
    -DUSE_STDPERIPH_DRIVER
    ; -D__SYSTEM_CLOCK_16M_IRC16M=16000000U
    -D__SYSTEM_CLOCK_64M_PLL_IRC16M=64000000U
